
# book_catalog Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: hiichloee.azurecr.io/book-catalog:2
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8000"
        - name: DATABASE_URL
          value: "postgresql://hiichloee:6zNXaWkwpu0VLbK7P5mCRPIkVJcq43dY@dpg-crjt8rd2ng1s73fkfdcg-a.singapore-postgres.render.com/chloe_sit722_55is"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
# inventory_management Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: hiichloee.azurecr.io/inventory-management:2 
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8001"
        - name: DATABASE_URL
          value: "postgresql://hiichloee:6zNXaWkwpu0VLbK7P5mCRPIkVJcq43dY@dpg-crjt8rd2ng1s73fkfdcg-a.singapore-postgres.render.com/chloe_sit722_55is"
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001